customers:
  mailDetails:
    from: default-customers@banking.com
    port: '9000'
    subject: Your customer Details from Banking Default Environment
    hostName: default-customers@banking.com
  build-version: '3'
  activeBranches: 
    - Mumbai
    - London
    - Washington
  msg: Welcome to the Banking customers Default application

server:
  port: '9000'
#  servlet:
#    context-path: '/banking'
    
## Configuring info endpoint
info:
  app:
    name: 'Customers Microservice'
    description: 'Banking Customers Application'
    version: '1.0.0'    
    
management:
  endpoint:
    shutdown:
      enabled: 'true'
  endpoints:
    web:
      exposure:
        include: '*'
        
endpoints:
  shutdown:
    enabled: 'true'
    
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: 'http://localhost:8080/eureka/'
      
resilience4j:
  circuitbreaker:
    instances:
      getCardsSupport:
        failureRateThreshold: '50'
        waitDurationInOpenState: '30000'
        minimumNumberOfCalls: '5'
        permittedNumberOfCallsInHalfOpenState: '2'
    configs:
      default:
        registerHealthIndicator: 'true'        
  retry:
    instances:
      getCustomerDetailsSupport:
        maxRetryAttempts: '3'
        waitDuration: '2000'
    configs:
      default:
        registerHealthIndicator: 'true'
  ratelimiter:
    instances:
      sayHello:
        limitRefreshPeriod: '5000'
        timeoutDuration: '5000'
        limitForPeriod: '1'
    configs:
      default:
        registerHealthIndicator: 'true'
        
spring:     
  sleuth:
    sampler:
      percentage: '1'
  zipkin:
    baseUrl: http://localhost:9411/  
