loans:
  mailDetails:
    from: default-loans@banking.com
    port: '9000'
    subject: Your loan Details from Banking Default Environment
    hostName: default-loans@banking.com
  build-version: '3'
  activeBranches: 
    - Mumbai
    - London
    - Washington
  msg: Welcome to the Banking loans Default application
  
server:
  port: '9020'
#  servlet:
#    context-path: '/banking'
    
## Configuring info endpoint
info:
  app:
    name: 'Loans Microservice'
    description: 'Banking Loans Application'
    version: '1.0.0'    
    
management:
  endpoint:
    shutdown:
      enabled: 'true'
  endpoints:
    web:
      exposure:
        include: '*'
        
endpoints:
  shutdown:
    enabled: 'true'
    
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: 'http://localhost:8080/eureka/'
      
spring:     
  sleuth:
    sampler:
      percentage: '1'
  zipkin:
    baseUrl: http://localhost:9411/      
