eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: '8080'
  
spring:     
  sleuth:
    sampler:
      percentage: '1'
  zipkin:
    baseUrl: http://localhost:9411/
